@startuml
skinparam ParticipantPadding 20
'skinparam BoxPadding 100

title HackerNews to discord
hide footbox

actor Klient


box "DevNews.CLI" #LightBlue
    boundary "Aplikacja" as App
    entity Dasboards.Api
end box

box "UniqueOne" #Orange
    boundary "ApiUniqueOne" as ApiUO

end box

autonumber
== Akcja w aplikacji rossmann.pl  ==
activate App
{start} Klient -> App : Klient uruchamia aplikacje
activate Dasboards.Api
App -> Dasboards.Api : Odpytanie api dostarczających dane o dashboardach
Dasboards.Api -> ApiUO : Odpytanie api o ilość losów dostępnych dla klienta
note right
{ userId: int }
autoryzacja secret key
end note
activate ApiUO
ApiUO -> Dasboards.Api : Zwrot danych o losach

deactivate ApiUO

== Wyświetlenie danych loterii ==
App <- Dasboards.Api : Zwrot danych dashboardów do aplikacji
deactivate Dasboards.Api
...
opt
    {end} Klient <<- App : Wyświetlenie dashboardu klientowi
    note left
    Ustalenie minimalnego poziomu opóźnien 
    jakie musi zapewnic nam UniqueOne
    end note
end
deactivate App

@enduml