name: Run Bot 

on:
  schedule:
    - cron: "00 11 * * 1"

env:
  DISCORD_WEBHOOK_TOKEN: "${{ secrets.DISCORD_WEBHOOK_TOKEN }}"
  DISCORD_WEBHOOK_ID: "${{ secrets.DISCORD_WEBHOOK_ID }}"
  MONGO_CONNECTION: "${{ secrets.DISCORD_WEBHOOK_ID }}"
  TEAMS_WEBHOOK_URL: "${{ secrets.TEAMS_WEBHOOK_URL }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Go Run
      run: make runbin
